window.onload=function(){
    new Vue({
        el:"#vue-app",
        data:{
            class0:{
                active:true,
            },
            class1:{
                active:false,
            },
            class2:{
                active:false,
            },
        },
        methods:{
            btn0:function(){           
                this.class0.active=true; 
                this.class1.active=false;           
                this.class2.active=false;
                fp.style.display="block";
                dp.style.display="none";
                lp.style.display="none";
            },
            btn1:function(){           
                this.class0.active=false; 
                this.class1.active=true;           
                this.class2.active=false;
                fp.style.display="none";           
                dp.style.display="block";
                lp.style.display="none";
            },
            btn2:function(){          
                this.class0.active=false; 
                this.class2.active=true;           
                this.class1.active=false;
                fp.style.display="none";
                dp.style.display="none";
                lp.style.display="block";
            },      
            mouseover0:function(){
                change0.style.border="1px solid #023c71";
                icon0.style.color="#023c71";
            },
            mouseout0:function(){
                change0.style.border="1px solid #ddd";
                icon0.style.color="#ddd";
            },  
            clickme0:function(){
                if(change0.style.height==("1000px"))
                {
                    change0.style.height="220px";                
                    icon0.style.transform="rotateX(0deg)";
                    icon0.style.left="8.5px";
                    dis0.style.display="none";
                    change1.style.height="220px";                
                    icon1.style.transform="rotateX(0deg)";
                    icon1.style.left="8.5px";
                    dis1.style.display="none";                
                }
                else{               
                    change0.style.height="1000px";
                    icon0.style.transform="rotateX(180deg)";
                    icon0.style.left="8.5px";              
                    dis0.style.display="block";
                    change1.style.height="220px";                
                    icon1.style.transform="rotateX(0deg)";
                    icon1.style.left="8.5px";
                    dis1.style.display="none";
                } 
                if(change1.style.height==("1000px"))
                {   
                    change1.style.height="220px";                
                    icon1.style.transform="rotateX(0deg)";
                    icon1.style.left="8.5px";
                    dis1.style.display="none";
                }
                else{
                    change1.style.height="220px";                
                    icon1.style.transform="rotateX(0deg)";
                    icon1.style.left="8.5px";
                    dis1.style.display="none";   
                }
            },  
            mouseover1:function(){
                change1.style.border="1px solid #023c71";
                icon1.style.color="#023c71";
            },
            mouseout1:function(){
                change1.style.border="1px solid #ddd";
                icon1.style.color="#ddd";
            },  
            clickme1:function(){
                if(change1.style.height==("1000px"))
                {   
                    change0.style.height="220px";                
                    icon0.style.transform="rotateX(0deg)";
                    icon0.style.left="8.5px";
                    dis0.style.display="none";
                    change1.style.height="220px";                
                    icon1.style.transform="rotateX(0deg)";
                    icon1.style.left="8.5px";        
                    dis1.style.display="none";               
                }
                else{ 
                    change0.style.height="220px";                
                    icon0.style.transform="rotateX(0deg)";
                    icon0.style.left="8.5px";
                    dis0.style.display="none";              
                    change1.style.height="1000px";
                    icon1.style.transform="rotateX(180deg)";
                    icon1.style.left="8.5px";
                    dis1.style.display="block";
                }
                if(change0.style.height==("1000px"))
                {        
                    change0.style.height="220px";                
                    icon0.style.transform="rotateX(0deg)";
                    icon0.style.left="8.5px"; 
                    dis0.style.display="none";          
                }
                else
                {      
                    change0.style.height="220px";                
                    icon0.style.transform="rotateX(0deg)";
                    icon0.style.left="8.5px"; 
                    dis0.style.display="none";   
                }
            },            
            mouseover2:function(){
                change2.style.border="1px solid #023c71";
                icon2.style.color="#023c71";
            },
            mouseout2:function(){
                change2.style.border="1px solid #ddd";
                icon2.style.color="#ddd";
            },   
            clickme2:function(){
                if(change2.style.height==("1000px"))
                {
                    change2.style.height="220px";                
                    icon2.style.transform="rotateX(0deg)";               
                    icon2.style.left="8.5px";
                    dis2.style.display="none"; 
                }
                else{               
                    change2.style.height="1000px";
                    icon2.style.transform="rotateX(180deg)";
                    icon2.style.left="8.5px";
                    dis2.style.display="block"; 
                }
            },     
            mouseover3:function(){
                change3.style.border="1px solid #023c71";
                icon3.style.color="#023c71";
            },
            mouseout3:function(){
                change3.style.border="1px solid #ddd";
                icon3.style.color="#ddd";
            },  
            clickme3:function(){
                if(change3.style.height==("1000px"))
                {
                    change3.style.height="220px";                
                    icon3.style.transform="rotateX(0deg)";
                    icon3.style.left="8.5px";
                    dis3.style.display="none"; 
                }
                else{               
                    change3.style.height="1000px";
                    icon3.style.transform="rotateX(180deg)";
                    icon3.style.left="8.5px";
                    dis3.style.display="block"; 
                }
            }, 
        }   
    });
    }